main/urls.py
from django.urls import path
from .views import index, filter_methods, about

app_name = 'main'
urlpatterns = [
    path('', index, name='index'),
    path('about', about, name='about'),
    path('filter_methods', filter_methods, name='filter_methods'),
]

table_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
]

main/models.py
from django.db import models

class Table(models.Model):
    date = models.DateTimeField(verbose_name='Дата')
    title = models.CharField(max_length=40, db_index=True, verbose_name="Название")
    quantity = models.IntegerField(db_index=True, verbose_name='Количество')
    distance = models.IntegerField(db_index=True, verbose_name='Расстояние')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        indexes = [
            models.Index(fields=['title', ]),
            models.Index(fields=['quantity', ]),
            models.Index(fields=['distance', ]),
        ]

main/forms.py
from django import forms

columns =    (
    ("", ""),
    ("Название", 'Название'),
    ("Количество", "Количество"),
    ("Расстояние", "Расстояние"),
)

filter_methods =    (
    ("", ""),
    ("Больше", "Больше"),
    ("Меньше", "Меньше"),
    ("Равно", "Равно"),
    ("Содержит", "Содержит"),
)

class FilterForm(forms.Form):
    column_name = forms.ChoiceField(choices=columns, required=True)
    filter_method = forms.ChoiceField(choices=filter_methods, required=True)
    value = forms.CharField(max_length=20, required=True)

    column_name.widget.attrs.update({'class': 'form-control', 'required': 'required'})
    filter_method.widget.attrs.update({'class': 'form-control', 'required': 'required'})
    value.widget.attrs.update({'class': 'form-control', 'required': 'required'})

main/views.py
from django.shortcuts import render
from .models import Table
from django.core.paginator import Paginator
from .forms import FilterForm
from django.contrib import messages


def index(request):
     '''Главная страница с формами фильтрации и пагинацией'''
     all_table_rows = Table.objects.all()
     paginator = Paginator(all_table_rows, 3)
     filter_form = FilterForm(request.POST)
     if 'page' in request.GET:
         page_num = request.GET['page']
     else:
         page_num = 1
     page = paginator.get_page(page_num)
     context = {'page': page, 'page_rows': page.object_list, 'filter_form': filter_form}
     return render(request, 'main/index.html', context)


def about(request):
    '''Информация о проекте'''
    return render(request, 'main/about.html')


def filter_methods(request):
    '''Обновление главной страницы с результатами фильтрации'''
    fitering_data = Table.objects.all()
    filter_form = FilterForm()
    if request.method == 'GET':
        if 'column_name' in request.GET:
            filter_form = FilterForm(request.GET)
            column_name = filter_form.data['column_name']
            filter_method = filter_form.data['filter_method']
            value = filter_form.data['value']
            if filter_method == "Больше":
                if column_name == 'Количество':
                    fitering_data = fitering_data.filter(quantity__gt=value)
                elif column_name == 'расстояние':
                    fitering_data = fitering_data.filter(distance__gt=value)
            if filter_method == "Меньше":
                if column_name == 'Количество':
                    fitering_data = fitering_data.filter(quantity__lt=value)
                elif column_name == 'расстояние':
                    fitering_data = fitering_data.filter(distance__lt=value)
            if filter_method == "Равно":
                if column_name == 'Количество':
                    fitering_data = fitering_data.filter(quantity=value)
                elif column_name == 'расстояние':
                    fitering_data = fitering_data.filter(distance=value)
                elif column_name == 'Название':
                    fitering_data = fitering_data.filter(title=value)
            if filter_method == "Содержит":
                if column_name == 'Название':
                    fitering_data = fitering_data.filter(title__icontains=value)
            messages.add_message(request, messages.SUCCESS, 'Объявление добавлено')
            filter_form = FilterForm(
                initial={'column_name': column_name, 'filter_method': filter_method, 'value': value})
        paginator = Paginator(fitering_data, 3)
        if 'page' in request.GET:
            page_num = request.GET['page']
        else:
            page_num = 1
        page = paginator.get_page(page_num)
        context = {'page': page, 'page_rows': page.object_list, 'filter_form': filter_form}
        return render(request, 'main/index.html', context)

main/templates/main/about.html
{% extends 'main/base.html' %}

{% block title %}Главная страница{% endblock %}
{% block content %}
    <div class="container">
    <h2>О проекте </h2>
    <p>Задание - https://faint-adasaurus-4bc.notion.site/web-Python-adf33211e9cc4d6b9ec2c0c619ecab31</p>

    <p class="fw-bold">Выполнено:</p>
        <ul>
        <li>Таблица содержит 4 колоноки</li>
        <li>База данных PostgreSQL</li>
        <li>Таблица имеет сортировку по всем полям кроме даты. Фильтрация реализована в виде двух выпадающих списков и текстового поля:</li>
            <ol>
            <li> Выбор колонки, по которой будет фильтрация</li>
            <li> Выбор условия (равно, содержит, больше, меньше)</li>
            <li> Поле для ввода значения для фильтрации</li>
            </ol>
        <li> Таблица содержит пагинацию</li>
        </ul>
    <p class="fw-bold">Не выполнено:</p>
        <ul><li>Вся таблица должна работать без перезагрузки страницы</li></ul>
    Причина:
        <ul><li>не удалось настроить работу ajax с сохранением пагинации</li></ul>
        <br>
    <p class="fw-bold">Примечание:</p>
        Исходя из содержания столбцов логика фильтации реализована следующим образом:
        <ul>
            <li>Функции фильтрации "Больше", "Меньше", не работают с полем "Название"</li>
            <li>Функция фильтрации "Содержит", не работает с полями "Количество" и "Расстояние"</li>
        </ul>
    <p class="fw-bold">Для начала работы, в файле settings.py, требуется указать параметры подключения к базе PostgreSQL </p>
    </div>
{% endblock %}

main/templates/main/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
            integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
            integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
            crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
  <span class="navbar-brand">WelbeX test project</span>
  <div class="navbar-nav-scroll">
    <ul class="navbar-nav bd-navbar-nav flex-row">
      <li class="nav-item mx-5">
        <a class="nav-link font-weight-bold text-white" href="{% url 'main:index' %}">Главная</a>
      </li>
      <li class="nav-item">
        <a class="nav-link font-weight-bold text-white" href="{% url 'main:about' %}">О проекте</a>
      </li>
    </ul>
  </div>
      </div>
</nav>
{% block content %}{% endblock %}
</body>
</html>

main/templates/main/index.html
{% extends 'main/base.html' %}

{% block title %}Главная страница{% endblock %}
{% block content %}
<div class="container">
<div class="row col-6 pb-3">
    <form method="get" id="filter_form" action="{% url 'main:filter_methods' %}">
        <h5>Выберите столбец:</h5>
        {{ filter_form.column_name }}
        <h5>Выберите метод фильтрации:</h5>
        {{ filter_form.filter_method }}
        <h5>Введите значение:</h5>
        {{ filter_form.value }} <br>
        <button class="btn btn-success" type="submit">Применить фильтр</button>
    </form>
</div>
<div class="container" id="refresh">
    <table id="myTable" class="demotable table table-striped table-bordered">
    <thead class="table-primary">
        <tr>
        <th scope="col" class="text-center">Дата</th>
        <th scope="col" class="text-center">Название</th>
        <th scope="col" class="text-center">Количество</th>
        <th scope="col" class="text-center">Расстояние</th>
        </tr>
    </thead>
    <tbody class="table-secondary">
        {% for rows in page_rows %}
        <tr class="text-center">
        <td>{{ rows.date }}</td>
        <td>{{ rows.title }}</td>
        <td>{{ rows.quantity }}</td>
        <td>{{ rows.distance }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>
<nav aria-label="Page navigation example">
    <ul class="pagination">
        {# Пагинация, если не применены фильтры #}
        {% if page.has_previous and all == '' %}
             <li class="page-item"><a class="page-link" href="">&laquo; first</a></li>
             <li class="page-item"><a class="page-link" href="?page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
        {% endif %}
        {% if all == '' %}
        <li class="page-item"><a class="page-link link-dark" href="#">{{ page.number }}</a></li>
        {% endif %}
        {% if page.has_next and all == '' %}
             <li class="page-item"><a class="page-link" href="?page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
             <li class="page-item"><a class="page-link" href="?page={{ page.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}

        {# Пагинация, если применены фильтры #}
        {% if page.has_previous and all != '' %}
             <li class="page-item"><a class="page-link" href="{{ all }}&page=1">&laquo; first</a></li>
             <li class="page-item"><a class="page-link" href="{{ all }}&page={{ page.previous_page_number }}">{{ page.previous_page_number }}</a></li>
        {% endif %}
        {% if all != '' %}
        <li class="page-item"><a class="page-link link-dark" href="#">{{ page.number }}</a></li>
        {% endif %}
        {% if page.has_next and all != '' %}
             <li class="page-item"><a class="page-link" href="{{ all }}&page={{ page.next_page_number }}">{{ page.next_page_number }}</a></li>
             <li class="page-item"><a class="page-link" href="{{ all }}&page={{ page.paginator.num_pages }}">last &raquo;</a></li>
        {% endif %}
  </ul>
</nav>
</div>
{% endblock %}